systems:
  basedir: "./logs"

model:
  N_voxel_init: 262144

  # We heuristically set initial time_grid and final time grid. 
  # A common strategy to set these two parameters for DNeRF dataset is:
  # We empirically set time_grid_final = int(0.24 * N_frames), and time_grid_final = int(0.5 * time_grid_final)
  # We show N_frames for each video 
  # "standup": 150; "jumpingjacks": 200; "hook"   : 100; "bouncingballs": 150
  # "lego"   :  50; "hellwarrior" : 100; "mutant" : 150; "trex"         : 200
  time_grid_init: 16   
  time_grid_final: 24
  upsampling_type: unaligned
  upsample_list: [3000, 6000, 9000]
  update_emptymask_list: [4000, 8000, 10000]


data:
  datadir: "./data/mini" #car_fusion
  scene_bbox_min: [-1.5, -1.5, -1.5] #[-2.7917263164153434, -0.1970594704567569, 5.29225856818257] #[0.0012811726, -0.0005490432, -0.0123098325]
  scene_bbox_max: [1.5, 1.5, 1.5] #[-2.3107194730629503, -0.1681727955518061, 5.529625896847164] # [0.004228488, 0.0002489506, -0.004190719] #
  downsample: 2.0

optim:
  n_iters: 25000

render_test: True
render_path: True
expname: mini_ogBB
